# Generated by Django 4.1.1 on 2022-09-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_followerscount_likepost_post_useraccount_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='id_user',
            field=models.IntegerField(default=0),
        ),
    ]
